### ISSUE TITLE
Update to Swift 5.0.1 breaks builds on Ubuntu 18/04

### ISSUE THREAD

**Issue by dankorotin** [swiftlang/swift-docker#138]
This commit breaks builds on Ubuntu 18.04: https://github.com/apple/swift-docker/commit/724a1d10c12da1006c1433da4e521894aaf14ef0#diff-a3be029562676b6e61a37c312894681e Everything worked fine with the previous release of this Dockerfile.

Somehow it got released despite failing tests on this version of OS: https://ci.swift.org/job/swift-docker-PR-linux/27/console#console-section-2

STR: Use this image and try to compile a Swift project

Result: Missing `openssl` and `zlib`. Output:
```
'swift-nio-ssl-support' openssl.pc: warning: couldn't find pc file
'swift-nio-zlib-support' zlib.pc: warning: couldn't find pc file
[1/50] Compiling CNIOZlib empty.c
[2/50] Compiling CNIOSHA1 c_nio_sha1.c
[3/50] Compiling CNIOOpenSSL shims.c
[4/50] Compiling CNIOOpenSSL helpers.c
[5/50] Compiling CNIOLinux shim.c
[6/50] Compiling CNIOLinux ifaddrs-android.c
In file included from /app/.build/checkouts/swift-nio-ssl/Sources/CNIOOpenSSL/helpers.c:14:
/app/.build/checkouts/swift-nio-ssl/Sources/CNIOOpenSSL/include/c_nio_openssl.h:17:10: fatal error: 'openssl/conf.h' file not found
#include <openssl/conf.h>
         ^~~~~~~~~~~~~~~~
In file included from /app/.build/checkouts/swift-nio-ssl/Sources/CNIOOpenSSL/shims.c:16:
/app/.build/checkouts/swift-nio-ssl/Sources/CNIOOpenSSL/include/c_nio_openssl.h:17:10: fatal error: 'openssl/conf.h' file not found
#include <openssl/conf.h>
         ^~~~~~~~~~~~~~~~
```

Expected result: successful build.

**Comment by ianpartridge** [comment]
The removal of certain packages was intentional in https://github.com/apple/swift-docker/commit/966cfdef637e319d28b681e42bdb905b070bf338.

The Swift images are intended to contain the minimum set of packages needed to build and run Swift programs.  zlib and OpenSSL development headers are not required by every Swift program - as you can see they are dependencies of SwiftNIO, not Swift.

Please add the packages SwiftNIO needs in your `Dockerfile`.

**Comment by dankorotin** [comment]
Thanks!

**Comment by ianpartridge** [comment]
You're welcome.  Sorry for the inconvenience but this is worth it for keeping the images as slim as possible for all users.

**Comment by dankorotin** [comment]
Just in case someone else runs into the same problem with SwiftNIO dependencies (mine was a part of a Vapor app): all you need is `apt-get install -y libssl-dev libicu-dev`.

**Comment by valeriomazzeo** [comment]
Using a Vapor 3 project that uses SwiftNIO I had to install only `libssl-dev`.

**Comment by ianpartridge** [comment]
Thanks for the info.  I think when Vapor 4 is released you won't even need that, because SwiftNIO 2 does not require a system `libssl`.

**Comment by tanner0101** [comment]
Vapor 4 still needs OpenSSL for crypto. Adding these two packages gets things working for me:
`libssl-dev zlib1g-dev`

**Comment by ianpartridge** [comment]
Ah cool, thanks Tanner.

**Comment by MihaelIsaev** [comment]
What about macOS 10.14.5 (fresh install) with Swift 5.0.1, how to fix `'openssl/conf.h' file not found` on it?

**Comment by MihaelIsaev** [comment]
Hahah, fixed just by regenerating xcodeproj 🙂 the problem appeared just because I copied project from another machine instead of doing `git clone && swift package generate-xcodeproj`
